#######
# Run #
#######

DOCKER_RUN = docker run \
	--rm \
	--volume $(DIR):$(app_dir) \
	--workdir $(app_dir) \
	--tty --interactive \
	--env DOCKER=1 \
	--env USER_ID=$(shell id -u) \
	--env GROUP_ID=$(shell id -g) \
	$(DOCKER_OPTIONS) \
	$(DOCKER_IMAGE):$(if $(DOCKER_TAG),$(DOCKER_TAG),latest)
