MANALA_RSYNC = rsync \
	--verbose --human-readable --itemize-changes \
	--archive --cvs-exclude --delete --delete-excluded --force \
	--compress \
	$(if $(MANALA_RSYNC_RSH),--rsh="$(MANALA_RSYNC_RSH)") \
